### ISSUE TITLE
No fontemon_blender_addon.zip

### ISSUE THREAD

**Issue by FreddieRa** [mmulet/code-relay#12]
After extracting on Windows 10, there was was only an unzipped folder. This was easily fixed by zipping the folder and using that for the Blender addon install, but the tutorial doesn't show this, it assumes it's there already:

![image](https://user-images.githubusercontent.com/14854492/113442726-80f27080-93e8-11eb-9208-ff4bc51590df.png)

**Comment by mmulet** [comment]
Good catch! I meant to commit it, but maybe it was already in .gitignore so it didn't add. I'll fix it add add it to the repo. Thanks.

**Comment by mmulet** [comment]
Fixed in commit https://github.com/mmulet/font-game-engine/commit/56ca281abedeaf875e4fc871cf65674f79cd3e25
