### ISSUE TITLE
Certificate issue on https://coderelay.io/

### ISSUE THREAD

**Issue by noelleleigh** [mmulet/code-relay#5]
When visiting <https://coderelay.io/>, browsers show a security message:

> Websites prove their identity via certificates. Firefox Developer Edition does not trust this site because it uses a certificate that is not valid for coderelay.io. The certificate is only valid for the following names: w<span>ww</span>.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com
>
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

Visiting <https://www.coderelay.io/> does not produce this message and works fine.

I noticed this issue when clicking on the "fontemon" link in [HowIDidIt.md](https://github.com/mmulet/code-relay/blob/main/markdown/HowIDidIt.md).

**Comment by mmulet** [comment]
Hmm, this site is hosted on GitHub. So I think I must have configured it incorrectly. Do you see any links that point to codereay.io instead of www.coderelay <http://www.coderelay.up/>.io? I will work on fixing this issue. Thanks for letting me know!

**Comment by noelleleigh** [comment]
> Hmm, this site is hosted on GitHub. So I think I must have configured it incorrectly. Do you see any links that point to codereay.io instead of [www.coderelay](http://www.coderelay) <http://www.coderelay.up/>.io? I will work on fixing this issue. Thanks for letting me know!

I've updated my initial comment to include where I found the problem. I haven't done a thorough scan for other links in the repository.

Do you think it's possible to add `coderelay.io` to the certificate and setup a redirect to `www.coderelay.io`?

**Comment by mmulet** [comment]
I’m looking at the docs now, https://docs.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages and I don’t see anyplace to enter multiple domains. Is it something simple like a comma or a slash? I set up the www subdomain because that’s what the docs recommended. Maybe I have to setup the apex domain a redirect to the www subdomain?

**Comment by noelleleigh** [comment]
> I’m looking at the docs now, https://docs.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages and I don’t see anyplace to enter multiple domains. Is it something simple like a comma or a slash? I set up the www subdomain because that’s what the docs recommended. Maybe I have to setup the apex domain a redirect to the www subdomain?

Those docs seem to have the answer?

> If you configure the correct records for each domain type through your DNS provider, GitHub Pages will automatically create redirects between the domains. For example, if you configure `www.example.com` as your custom domain for your site, and you have `ALIAS` and `CNAME` records set up for the apex and `www` domains, then `example.com` will redirect to `www.example.com`.

**Comment by mmulet** [comment]
Alright I think I’ve found the issue. The site is getting a lot of traffic right now, so I’m going to hold off on making any changes until tomorrow. Thanks again!

**Comment by noelleleigh** [comment]
Any updates on this?

**Comment by noelleleigh** [comment]
Looks like this has been fixed!
