### ISSUE TITLE
Submit to SIGBOVIK

### ISSUE THREAD

**Issue by wbt** [mmulet/code-relay#6]
You are very much invited to submit this project to [SIGBOVIK](http://www.sigbovik.org/) ([2021 event page](http://www.sigbovik.org/2021/)) if you haven't already; it would fit right in.  Though the paper deadline is nominally today, you can present (<=5 min) without having submitted a paper, and you can submit a paper for next year.  Feel free to check out the archives and/or attend the 2021 edition for your entertainment.

**Comment by mmulet** [comment]
This sounds hilarious. I will definitely do that, can my paper be written in the Fotemon font?

**Comment by wbt** [comment]
Not sure if it'd work, but that would be hilarious!  Also they just extended the deadline a week so you can do a good job on it :-)

**Comment by mmulet** [comment]
If anyone reads this in the future, you can read the fontemon sigbovik paper here: http://www.sigbovik.org/2021/proceedings.pdf#page=41
